[package]
name = "bats-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bats-dsp = { path = "../bats-dsp" }
bats-lib = { path = "../bats-lib" }
crossbeam-channel = "0.5"