[package]
name = "bmidi"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies.criterion]
criterion = { version = "0.4", features = ["html_reports"], default_features = false }
