name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install liblilv-dev lv2-examples mda-lv2 jackd libjack0 libjack-dev guile-3.0-dev
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Lint
        run: cargo clippy || echo Cargo Clippy Failed
      - name: Build
        run: cargo build --verbose
      - name: Run Rust tests
        run: RUST_TEST_THREADS=1 cargo test --verbose
      - name: Run Scheme tests
        run: guile ./tests/test.scm
