name: Testing
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
env:
    CARGO_TERM_COLOR: always
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
               sudo apt update
               # Most users will be on JACK spa (aka pipewire), but
               # pipewire is harder to set up on GitHub actions.
               sudo apt install jackd libjack-dev libjack0 liblilv-dev
               # Required for tests.
               sudo apt install mda-lv2
            - name: Run JACK server
              run: jackd -r -ddummy -r44100 -p1024 &
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Lint
              run: cargo clippy || echo -e "\e[31mcargo clippy failed\f[0m"
            - name: Build
              run: cargo build --verbose
            - name: Test
              run: cargo test --verbose
