name: Testing
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
env:
    CARGO_TERM_COLOR: always
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
               sudo apt update
               # Most users will be on JACK spa (aka pipewire), but
               # pipewire is harder to set up on GitHub actions.
               sudo apt install jackd libjack-dev libjack0
            - name: Run JACK server
               jackd -ddummy &
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Lint
              run: cargo clippy | echo Lint Failed
            - name: Build
              run: cargo build --verbose
            - name: Test
              run: cargo test --verbose
