name: Testing
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
env:
    CARGO_TERM_COLOR: always
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: |
               sudo apt update
               sudo apt install libjack-dev libspa-0.2-jack
               jackd -ddummy &
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Lint
              run: cargo clippy | echo Lint Failed
            - name: Build
              run: cargo build --verbose
            - name: Test
              run: cargo test --verbose
